# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='location',
            new_name='clocation',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='location',
            new_name='rlocation',
        ),
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serve.restaurant'),
        ),
    ]
